# ===== PRODUCCIÓN (EC2) =====

spring.datasource.url=jdbc:mysql://localhost:3306/lecturasana_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# NO borrar tablas en producción
spring.jpa.hibernate.ddl-auto=update

# NO ejecutar data.sql en producción
spring.sql.init.mode=never

# Actuator health para validación
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# (Opcional) menos ruido en logs
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO